trigger:
  branches:
    include:
      - main  # Runs pipeline when code is pushed to main

pool:
  vmImage: 'windows-latest'  # Use Windows for building .exe

steps:
  - checkout: self  # Get the code from GitHub

  - task: UsePythonVersion@1
    inputs:
      versionSpec: '3.x'  # Ensure Python is available

  - script: |
      powershell -ExecutionPolicy Unrestricted -File build.ps1
    displayName: 'Run Build Script'

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: 'Executables/'  # Adjust this to where your .exe is stored
      artifactName: 'azure_build_latest'  # Name of the artifact
