trigger:
  branches:
    include:
      - main
  paths:
    exclude:
      - Executables/*
  

pool:
  vmImage: 'windows-latest'

steps:
  - checkout: self

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'

  - script: mkdir Executables
    displayName: 'Ensure Executables Folder Exists'
    condition: always()

  - script: |
      powershell -ExecutionPolicy Unrestricted -File build.ps1
    displayName: 'Run Build Script'

  - script: |
      dir Executables
    displayName: 'Check Executables Folder'

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: 'Executables/'  # Adjust based on actual output
      artifactName: 'azure_build_latest'

  - script: |
      git config --global user.email "artmole.niko@gmail.com"
      git config --global user.name "Azure DevOps"
      git add Executables/
      git commit -m "Update executable from latest build"
      git push
    displayName: 'Commit and Push to GitHub'
